### ISSUE TITLE
Feature request: set user PIN code

### ISSUE THREAD

**Issue by andreassolberg** [TedTolboom/no.IDLock#26]
Set `COMMAND_CLASS_USER_CODE_V1` 0x63 according to the manual.

**Comment by erlingtei** [comment]
This would be great to have. Also setting service PIN that are valid a certain period of time would be awesome. The manual is here: [https://idlock.no/wp-content/uploads/2019/08/IDLock150_ZWave_UserManual_v3.02.pdf](https://idlock.no/wp-content/uploads/2019/08/IDLock150_ZWave_UserManual_v3.02.pdf)

**Comment by hornbriller** [comment]
I support this request 👍  It would be good to be able to fully control and manage pin codes from within the app. It seems that I can add pin codes under “Configure app” --> “Code/Tag Mappings” --> “Add Code”. However, none of the codes that I have set through the lock itself appear here. It would be good to be able to control all the codes from the app, give them names (of the users), in order to get a notification when a certain code is used (e.g. when the kids are home from school, or a time-limited service code has been used to unlock the door).

Looking forward to your reply! Keep up the good work! 😃

**Comment by MbenzNo** [comment]
I would also love to be able to set user PIN and Service PIN valid time! 
I am really looking forward/hoping for any further developement af the app

**Comment by TedTolboom** [comment]
Resolved in v2.0.0

**Comment by itzbolsi** [comment]
@TedTolboom how do we set user pin codes in the new app? Cant find it any where.

**Comment by MbenzNo** [comment]
> @TedTolboom how do we set user pin codes in the new app? Cant find it any where.

Same here...

**Comment by runely** [comment]
This isn't implemented in v2.0.0

v2.0.0 has these changes:
- Added support for firmware v1.6 of the ZWave chip (enable this in the advanced setting on the device in homey)
- Rewritten to SDK3 to support Homey Pro 2023
- Added Norwegian locale
