### ISSUE TITLE
Draining batteries

### ISSUE THREAD

**Issue by bananfluen** [TedTolboom/no.IDLock#4]

**Comment by TedTolboom** [comment]
Hello @bananfluen,

Apologies for the late response, somehow this issue did not send the right trigger to me to notify me about this issue.

I do recognize the issue from other reports... 
some reported that only installing 4 out of 8 batteries worked better...

Since I don’t have access to an IDLock myself, I’m not able to reproduce / further investigate the issue myself..
I’ll check with IDLock myself if we can figure out what the issue is or can be.

**Comment by TedTolboom** [comment]
@bananfluen if you update to the latest firmware version as suggested above; does this solve the battery draining issue?

**Comment by bananfluen** [comment]
I think this is only for ID Lock 150 `?

**Comment by jogegot** [comment]
Updated to 1.2.0 and my batteries drained in just a few hours on my idlock 101
